spring:
  datasource:
    url: jdbc:p6spy:mysql://10.30.7.152:3306/qu_thanos?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: dev_owner
    password: ziroomdb
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    initialization-mode: embedded
    hikari:
      initialSize: 5
      minIdle: 5
      maxActive: 10
  redis:
    host: 10.216.4.116
    port: 6384
    timeout: 2000
  mail:
    host: smtp.xxx.xxx
    username: xxxx@xxx.xxx
    password: xxxxxx
    port: 25
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

jiraIssue:
  validateFlag: false
jira:
  baseurl: http://jira.xxxx.com/
  username: admin
  password: admin123

ziroom:
  ehr:
    defendeRediskey: myRedisKey

quality:
  baseurl: http://localhost:8080/
  testTaskUrl: http://localhost:8080/caseExecutionDetailAndList?type=add

